--------------------------------------------------------
--  파일이 생성됨 - 월요일-3월-04-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table VOTE
--------------------------------------------------------

  CREATE TABLE "SCOTT"."VOTE" 
   (	"USER_ID" VARCHAR2(100 BYTE), 
	"SURVEY_NUM" NUMBER, 
	"COL_NUMBER" NUMBER(1,0), 
	"CHOICE_NUM" NUMBER(1,0) DEFAULT 1
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SURVEY
--------------------------------------------------------

  CREATE TABLE "SCOTT"."SURVEY" 
   (	"SURVEY_NUM" NUMBER, 
	"COL_NUMBER" NUMBER(1,0), 
	"TITLE" VARCHAR2(50 CHAR), 
	"START_DATE" DATE DEFAULT SYSDATE, 
	"END_DATE" DATE DEFAULT SYSDATE + 7, 
	"WRITE_DATE" TIMESTAMP (6) DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ITEM
--------------------------------------------------------

  CREATE TABLE "SCOTT"."ITEM" 
   (	"CHO_NUM" VARCHAR2(100 BYTE), 
	"SURVEY_NUM" NUMBER, 
	"COL_NUMBER" NUMBER(1,0), 
	"CHOICE1" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EDIT
--------------------------------------------------------

  CREATE TABLE "SCOTT"."EDIT" 
   (	"SURVERY_NUM" NUMBER, 
	"ADMIN_ID" VARCHAR2(100 BYTE), 
	"COL_NUMBER" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ADMINISTRATOR
--------------------------------------------------------

  CREATE TABLE "SCOTT"."ADMINISTRATOR" 
   (	"ADMIN_ID" VARCHAR2(100 BYTE), 
	"NAME" VARCHAR2(100 BYTE), 
	"EMAILADDRESS" VARCHAR2(100 BYTE), 
	"BIRTHDATE" DATE DEFAULT sysdate, 
	"NICKNAME" VARCHAR2(80 BYTE), 
	"PASSWORD" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_VOTE
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."PK_VOTE" ON "SCOTT"."VOTE" ("USER_ID", "SURVEY_NUM", "COL_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_SURVEY
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."PK_SURVEY" ON "SCOTT"."SURVEY" ("SURVEY_NUM", "COL_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ITEM
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."PK_ITEM" ON "SCOTT"."ITEM" ("CHO_NUM", "SURVEY_NUM", "COL_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_EDIT
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."PK_EDIT" ON "SCOTT"."EDIT" ("SURVERY_NUM", "ADMIN_ID", "COL_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ADMINISTRATOR
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."PK_ADMINISTRATOR" ON "SCOTT"."ADMINISTRATOR" ("ADMIN_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EMAILUNIQUE
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."EMAILUNIQUE" ON "SCOTT"."ADMINISTRATOR" ("EMAILADDRESS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index NICUNIQUE
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."NICUNIQUE" ON "SCOTT"."ADMINISTRATOR" ("NICKNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table VOTE
--------------------------------------------------------

  ALTER TABLE "SCOTT"."VOTE" ADD CONSTRAINT "PK_VOTE" PRIMARY KEY ("USER_ID", "SURVEY_NUM", "COL_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SCOTT"."VOTE" MODIFY ("CHOICE_NUM" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."VOTE" MODIFY ("COL_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."VOTE" MODIFY ("SURVEY_NUM" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."VOTE" MODIFY ("USER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SURVEY
--------------------------------------------------------

  ALTER TABLE "SCOTT"."SURVEY" ADD CONSTRAINT "CK_SURVEY_TO_WIRTE_DATE" CHECK (write_date <= start_date) ENABLE;
  ALTER TABLE "SCOTT"."SURVEY" ADD CONSTRAINT "CK_SURVEY_TO_START_DATE" CHECK (start_date <= end_date) ENABLE;
  ALTER TABLE "SCOTT"."SURVEY" ADD CONSTRAINT "CK_SURVEY_TO_COL_NUMBER" CHECK (col_number >=2) ENABLE;
  ALTER TABLE "SCOTT"."SURVEY" ADD CONSTRAINT "CK_SURVEY_TO_SURVEY_NUM" CHECK (survey_num >=1) ENABLE;
  ALTER TABLE "SCOTT"."SURVEY" ADD CONSTRAINT "PK_SURVEY" PRIMARY KEY ("SURVEY_NUM", "COL_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SCOTT"."SURVEY" MODIFY ("WRITE_DATE" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."SURVEY" MODIFY ("END_DATE" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."SURVEY" MODIFY ("START_DATE" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."SURVEY" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."SURVEY" MODIFY ("COL_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."SURVEY" MODIFY ("SURVEY_NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ITEM
--------------------------------------------------------

  ALTER TABLE "SCOTT"."ITEM" ADD CONSTRAINT "PK_ITEM" PRIMARY KEY ("CHO_NUM", "SURVEY_NUM", "COL_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SCOTT"."ITEM" MODIFY ("CHOICE1" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."ITEM" MODIFY ("COL_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."ITEM" MODIFY ("SURVEY_NUM" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."ITEM" MODIFY ("CHO_NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EDIT
--------------------------------------------------------

  ALTER TABLE "SCOTT"."EDIT" ADD CONSTRAINT "PK_EDIT" PRIMARY KEY ("SURVERY_NUM", "ADMIN_ID", "COL_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SCOTT"."EDIT" MODIFY ("COL_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."EDIT" MODIFY ("ADMIN_ID" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."EDIT" MODIFY ("SURVERY_NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ADMINISTRATOR
--------------------------------------------------------

  ALTER TABLE "SCOTT"."ADMINISTRATOR" ADD CONSTRAINT "NICUNIQUE" UNIQUE ("NICKNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SCOTT"."ADMINISTRATOR" ADD CONSTRAINT "EMAILUNIQUE" UNIQUE ("EMAILADDRESS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SCOTT"."ADMINISTRATOR" ADD CONSTRAINT "IDCONSTR" CHECK (admin_id like '#%') ENABLE;
  ALTER TABLE "SCOTT"."ADMINISTRATOR" ADD CONSTRAINT "PK_ADMINISTRATOR" PRIMARY KEY ("ADMIN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SCOTT"."ADMINISTRATOR" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."ADMINISTRATOR" MODIFY ("NICKNAME" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."ADMINISTRATOR" MODIFY ("BIRTHDATE" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."ADMINISTRATOR" MODIFY ("EMAILADDRESS" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."ADMINISTRATOR" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."ADMINISTRATOR" MODIFY ("ADMIN_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table VOTE
--------------------------------------------------------

  ALTER TABLE "SCOTT"."VOTE" ADD CONSTRAINT "FK_MEMBER_TO_VOTE_1" FOREIGN KEY ("USER_ID")
	  REFERENCES "SCOTT"."MEMBER" ("USER_ID") ENABLE;
  ALTER TABLE "SCOTT"."VOTE" ADD CONSTRAINT "FK_SURVEY_TO_VOTE_1" FOREIGN KEY ("SURVEY_NUM", "COL_NUMBER")
	  REFERENCES "SCOTT"."SURVEY" ("SURVEY_NUM", "COL_NUMBER") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ITEM
--------------------------------------------------------

  ALTER TABLE "SCOTT"."ITEM" ADD CONSTRAINT "FK_SURVEY_TO_ITEM_1" FOREIGN KEY ("SURVEY_NUM", "COL_NUMBER")
	  REFERENCES "SCOTT"."SURVEY" ("SURVEY_NUM", "COL_NUMBER") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EDIT
--------------------------------------------------------

  ALTER TABLE "SCOTT"."EDIT" ADD CONSTRAINT "FK_ADMINISTRATOR_TO_EDIT_1" FOREIGN KEY ("ADMIN_ID")
	  REFERENCES "SCOTT"."ADMINISTRATOR" ("ADMIN_ID") ENABLE;
  ALTER TABLE "SCOTT"."EDIT" ADD CONSTRAINT "FK_SURVEY_TO_EDIT_1" FOREIGN KEY ("SURVERY_NUM", "COL_NUMBER")
	  REFERENCES "SCOTT"."SURVEY" ("SURVEY_NUM", "COL_NUMBER") ENABLE;
